.deploy_apt:
  stage: deploy
  variables:
    PACKAGE_FILE: homed-common_${CI_COMMIT_TAG}_${ARCHITECTURE}.deb
  script:
  - "cp -r deploy/apt deploy/data/DEBIAN"
  - "md5deep -lr deploy/data | grep -v DEBIAN | sed \"s+deploy/data/++g\" | sort -k2 > deploy/data/DEBIAN/md5sums"
  - "sed -i \"s+^Version:.*+Version: ${CI_COMMIT_TAG}+g\" deploy/data/DEBIAN/control"
  - "sed -i \"s+^Architecture:.*+Architecture: ${ARCHITECTURE}+g\" deploy/data/DEBIAN/control"
  - "fakeroot dpkg-deb --build deploy/data"
  - "mv deploy/data.deb ${PACKAGE_FILE}"
  - "reprepro -b /var/www/apt.homed.dev -C main includedeb debian ${PACKAGE_FILE}"
  artifacts:
    paths:
    - ${PACKAGE_FILE}
    expire_in: never
  rules:
  - if: $CI_COMMIT_TAG =~ /^\d.\d.\d+$/
    when: always
  - when: never

.deploy_opkg:
  stage: deploy
  variables:
    PACKAGE_FILE: homed-common_${CI_COMMIT_TAG}_${ARCHITECTURE}.ipk
    FEED_DIR: /var/www/opkg.homed.dev/${ARCHITECTURE}
  script:
  - "sed -i \"s+^Version:.*+Version: ${CI_COMMIT_TAG}+g\" deploy/opkg/control"
  - "sed -i \"s+^Architecture:.*+Architecture: ${ARCHITECTURE}+g\" deploy/opkg/control"
  - "echo \"2.0\" > debian-binary"
  - "fakeroot tar -czf control.tar.gz -C deploy/opkg ."
  - "fakeroot tar -czf data.tar.gz -C deploy/data ."
  - "fakeroot tar -czf ${PACKAGE_FILE} control.tar.gz data.tar.gz debian-binary"
  - "mkdir -p ${FEED_DIR}"
  - "rm -f ${FEED_DIR}/homed-common_*"
  - "cp ${PACKAGE_FILE} ${FEED_DIR}"
  - "/opt/scripts/opkgIndex.sh ${FEED_DIR} > ${FEED_DIR}/Packages"
  - "/opt/opkg/usign -S -m ${FEED_DIR}/Packages -s /opt/opkg/opkg.key -x ${FEED_DIR}/Packages.sig"
  - "gzip -fk ${FEED_DIR}/Packages"
  artifacts:
    paths:
    - ${PACKAGE_FILE}
    expire_in: never
  rules:
  - if: $CI_COMMIT_TAG =~ /^\d.\d.\d+$/
    when: always
  - when: never

Clone repository:
    script: "echo \"Common files for HOMEd services build\""

Deploy APT Package (amd64):
  extends: .deploy_apt
  variables:
    ARCHITECTURE: amd64

Deploy APT Package (aarch64):
  extends: .deploy_apt
  variables:
    ARCHITECTURE: aarch64

Deploy APT Package (arm64):
  extends: .deploy_apt
  variables:
    ARCHITECTURE: arm64

Deploy APT Package (armhf):
  extends: .deploy_apt
  variables:
    ARCHITECTURE: armhf

Deploy OpenWRT Package (aarch64_generic):
  extends: .deploy_opkg
  variables:
    ARCHITECTURE: aarch64_generic

Deploy OpenWRT Package (arm_cortex-a7_neon-vfpv4):
  extends: .deploy_opkg
  variables:
    ARCHITECTURE: arm_cortex-a7_neon-vfpv4

Deploy OpenWRT Package (arm_cortex-a9_neon):
  extends: .deploy_opkg
  variables:
    ARCHITECTURE: arm_cortex-a9_neon

Deploy OpenWRT Package (mips_24kc):
  extends: .deploy_opkg
  variables:
    ARCHITECTURE: mips_24kc

Deploy OpenWRT Package (mipsel_24kc):
  extends: .deploy_opkg
  variables:
    ARCHITECTURE: mipsel_24kc
